spring.application.name=ElenaFranconi
spring.config.import=optional:file:env.properties,optional:file:C:/Projects/ArtNaturaTeatro/SpringBoot/env.properties
#Server Port
server.port=${PORT}

#Postgres
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#JWT
spring.jwt.secret=${JWT_SECRET}

#FileSize
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.location=C:/Projects/ArtNaturaTeatro/SpringBoot/tmp

#Timeouts
server.connection-timeout=300000
spring.mvc.async.request-timeout=300000

#Images
image.upload.directory=C:/Projects/ArtNaturaTeatro/SpringBoot/uploads/
image.logo.directory=C:/Projects/ArtNaturaTeatro/SpringBoot/assets/logo/LOGO_ART_NO_BG_120.webp

#Email
spring.mail.host=smtps.aruba.it
spring.mail.port=465
spring.mail.username=${ARUBA_EMAIL}
spring.mail.password=${ARUBA_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

#URL
app.frontend.url=${FRONTEND_URL}